import 'package:flutter/material.dart';

class MappingList extends StatelessWidget {
  const MappingList({super.key});
  final List<Map<String, dynamic>> mylist = const [
    {
      "Name": "Rasyid",
      "Age": 21,
      "favColor": [
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
      ],
    },
    {
      "Name": "Prayogo",
      "Age": 20,
      "favColor": ["Amber", "Yellow", "Purple"],
    },
    {
      "Name": "Rasyid",
      "Age": 21,
      "favColor": [
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
      ],
    },
    {
      "Name": "Rasyid",
      "Age": 21,
      "favColor": [
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
      ],
    },
    {
      "Name": "Rasyid",
      "Age": 21,
      "favColor": [
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
      ],
    },
    {
      "Name": "Rasyid",
      "Age": 21,
      "favColor": [
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
      ],
    },
    {
      "Name": "Rasyid",
      "Age": 21,
      "favColor": [
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
        "Red",
        "Green",
        "Blue",
      ],
    },
  ];
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: Text("ID apps")),
        body: ListView(
          children: mylist.map((data) {
            List myfavcolor = data['favColor'];
            return Card(
              margin: EdgeInsets.all(20),
              color: Colors.black.withOpacity(0.1),
              child: Container(
                margin: EdgeInsets.all(10),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    //row
                    Row(
                      children: [
                        CircleAvatar(),
                        SizedBox(width: 20),
                        Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text("Name : ${data['Name']}"),
                            Text("Age : ${data['Age']}"),
                          ],
                        ),
                      ],
                    ),
                    //favcolor
                    SingleChildScrollView(
                      scrollDirection: Axis.horizontal,
                      physics: const BouncingScrollPhysics(),
                      primary: false,
                      child: Row(
                        children: myfavcolor.map((color) {
                          return Container(
                            color: Colors.amber,
                            margin: EdgeInsets.symmetric(
                              vertical: 15,
                              horizontal: 8,
                            ),
                            padding: EdgeInsets.all(10),
                            child: Text(color),
                          );
                        }).toList(),
                      ),
                    ),
                  ],
                ),
              ),
            );
          }).toList(),
        ),
      ),
    );
  }
}
